# Site settings
title: Cogito · ergo sum
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "Wen-Fei Cao|Cogito · ergo sum"  
baseurl: ""
url: "https://carlking5019.github.io"  

# About/contact
owner: 
  name: CarlKing5019
  email: CarlKing5019@gmail.com
  bio: ""

# Data
gavatar: 
favicon: img/favicon.png

douban_username: CarlKing5019
twitter_username: CarlKing5019
github_username: CarlKing5019
facebook_username: CarlKing5019
weibo_username: CarlKing5019 
zhihu_username: CarlKing5019

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai 

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CarlKing5019"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : CarlKing5019
  disqus :
      short_name : CarlKing5019

# Analytics and webmaster tools stuff goes here
google_analytics: 
# UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
