# Site settings
title: Wen-Fei Cao
header-img: "img/blue.jpg"
header-bg: blue
tagline: "homepage"  
description: "Homepage of Wen-Fei Cao"  
baseurl: ""
url: "https://carlking5019.github.io"  

# About/contact
owner: 
  name: CarlKing5019
  email: CarlKing5019@gmail.com
  bio: "Cogito · ergo sum"

# Data
gavatar: img/gavatar.png
favicon: img/favicon.png

douban_username: CarlKing5019
twitter_username: CarlKing5019
github_username: CarlKing5019
facebook_username: CarlKing5019
weibo_username: CarlKing5019 
zhihu_username: CarlKing5019

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
kramdown:
  input: GFM
  hard_wrap: false

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai 

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CarlKing5019"
      header-img: "img/blue.jpg"
      header-bg: blue


### template colors, used site-wide via css ###
colors:
  blue:              "#395791"
  dark-blue:         "#18556C"
  facebook-blue:     "#395791"
  trello-blue:       "#2F7BC0"
  twitter-blue:      "#4AA6EB"
  zhihu-blue:        "#1269C3"
  black:             "#4B4C4D"
  greeen:            "#F5F5F5"
  sea-green:         "#23B5AD"
  orange:            "#E18175"
  red:               "#EB695A"
  rose-red:          "#B25154"







# Comments 
# comments :
#   provider : disqus
#   duoshuo :
#     short_name : CarlKing5019
#   disqus :
#       short_name : CarlKing5019

# Analytics and webmaster tools stuff goes here
# google_analytics: 
# # UA-80884545-1
# google_verify:
# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Links to include in footer navigation
